language = "Typescript"
source_dir = "src"
 
[clickhouse_config]
db_name = "local"
user = "panda"
password = "pandapass"
use_ssl = false
host = "localhost"
host_port = 18123
native_port = 9000
 
[http_server_config]
host = "localhost"
port = 4000
management_port = 5001
 
 
[features]
streaming_engine = false
ddl_plan = true


